#!/bin/bash
# Morning Briefing — one-paste bootstrap.
# Run this on your Uber devpod (NOT your Mac):
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/LawlessTom/Slack-Bots/main/bootstrap.sh)
#
# (Note the `bash <(...)` form, not `curl | bash` — the latter feeds the script
# in via stdin, which interferes with the interactive prompts and ssh calls.)
#
# It will:
#   1. Verify prereqs (aifx, jq, git)
#   2. Clone the kit + run install.sh (HTTPS, no GitHub auth needed — public repo)
#   3. Auto-fill your email (FTE or ext contractor)
#   4. Embed the shared webhook URL
#   5. Launch Claude so you can OAuth google-mcp + slack-mcp (2 browser clicks)
#   6. Smoke-test the briefing — you should get a Slack DM within ~30s
#
# Total time: ~3 min. After this, cron fires daily at 8am Sydney time.

set -euo pipefail

KIT_REPO="https://github.com/LawlessTom/Slack-Bots.git"
KIT_DIR="$HOME/morning-briefing-kit"
ENV_FILE="$HOME/.config/morning-briefing.env"

# We need /dev/tty for interactive prompts because stdin is the curl pipe.
if [ ! -r /dev/tty ]; then
  echo "✗ No controlling terminal. Re-run inside an interactive shell on your devpod."
  exit 1
fi

bold()   { printf '\033[1m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
red()    { printf '\033[31m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }

echo ""
bold "═══════════════════════════════════════════════"
bold "  Morning Briefing — one-paste bootstrap"
bold "═══════════════════════════════════════════════"
echo ""

# ───────────────────────────────────────────────────────────
# 1. Prereqs
# ───────────────────────────────────────────────────────────
bold "[1/5] Checking prerequisites..."
for cmd in aifx git curl; do
  if ! command -v "$cmd" >/dev/null; then
    red "  ✗ '$cmd' not found. This script must run on an Uber devpod."
    exit 1
  fi
done
if ! command -v jq >/dev/null; then
  echo "  Installing jq..."
  sudo apt-get install -qq -y jq
fi
green "  ✓ aifx, git, curl, jq all present"

# ───────────────────────────────────────────────────────────
# 2. Clone kit (HTTPS — public repo, no auth needed)
# ───────────────────────────────────────────────────────────
bold "[2/5] Cloning the kit..."
if [ -d "$KIT_DIR/.git" ]; then
  echo "  Kit already exists at $KIT_DIR — pulling latest..."
  (cd "$KIT_DIR" && git pull --rebase --quiet)
else
  git clone --quiet "$KIT_REPO" "$KIT_DIR"
fi
green "  ✓ Kit at $KIT_DIR"

# ───────────────────────────────────────────────────────────
# 3. Run installer
# ───────────────────────────────────────────────────────────
bold "[3/5] Running installer..."
chmod +x "$KIT_DIR/install.sh"
"$KIT_DIR/install.sh"

# ───────────────────────────────────────────────────────────
# 4. Collect config interactively
# ───────────────────────────────────────────────────────────
echo ""
bold "[4/5] Configuring..."

# Determine email domain (FTE vs ext contractor)
echo ""
echo "  Are you an Uber FTE or external contractor?"
echo "    [1] FTE        (email will be ${USER}@uber.com)"
echo "    [2] ext        (email will be ${USER}@ext.uber.com)"
printf "  Choose [1/2 or fte/ext]: " > /dev/tty
read -r FTE_CHOICE < /dev/tty
case "$(echo "$FTE_CHOICE" | tr '[:upper:]' '[:lower:]')" in
  1|fte) RECIPIENT_EMAIL="${USER}@uber.com" ;;
  2|ext) RECIPIENT_EMAIL="${USER}@ext.uber.com" ;;
  *) RECIPIENT_EMAIL="${USER}@ext.uber.com"; yellow "  ! Unrecognised choice — defaulting to ext" ;;
esac
green "  ✓ Email: $RECIPIENT_EMAIL"

# Fetch webhook URL (embedded in the kit — see README for rotation note)
WEBHOOK_URL="https://hooks.slack.com/triggers/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"
green "  ✓ Webhook: embedded"

# Write env file (preserve KIT_DIR line if installer added it)
EXISTING_KIT_DIR=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_KIT_DIR=$(grep '^KIT_DIR=' "$ENV_FILE" 2>/dev/null || true)
fi

{
  echo "# Morning Briefing — generated by bootstrap.sh on $(date -Iseconds)"
  echo "WEBHOOK_URL=$WEBHOOK_URL"
  echo "RECIPIENT_EMAIL=$RECIPIENT_EMAIL"
  [ -n "$EXISTING_KIT_DIR" ] && echo "$EXISTING_KIT_DIR" || echo "KIT_DIR=$KIT_DIR"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
green "  ✓ Config written ($ENV_FILE, chmod 600)"

# ───────────────────────────────────────────────────────────
# 5. OAuth + smoke test
# ───────────────────────────────────────────────────────────
echo ""
bold "[5/5] OAuth + smoke test"
echo ""
yellow "  Claude will open in a moment. Type these THREE commands at the ❯ prompt — ONE AT A TIME, pressing Enter after each (do NOT paste all three together — Claude will treat them as one prompt and get confused):"
echo ""
echo "    list my next 3 google calendar events"
echo "    list my unread slack DMs from today"
echo "    /exit"
echo ""
yellow "  Each of the first two will print a URL — open it in your MAC browser"
yellow "  (not the devpod) to complete Uber SSO OAuth."
echo ""
printf "  Press Enter when ready to launch Claude... " > /dev/tty
read -r _ < /dev/tty

# Run interactively — needs /dev/tty for the TUI.
aifx agent run claude < /dev/tty || true

echo ""
bold "  Running smoke test..."
"$HOME/bin/run-morning-briefing.sh" || true

LOG_FILE="$HOME/.claude/logs/morning-briefing-$(date +%Y%m%d).log"
if grep -q '"ok":true' "$LOG_FILE" 2>/dev/null; then
  green "  ✓ Webhook accepted — check Slack for a DM from 'Morning Briefing Notifier'"
else
  yellow "  ⚠ Couldn't confirm webhook success. Inspect the log:"
  echo "      tail -200 $LOG_FILE"
fi

echo ""
bold "═══════════════════════════════════════════════"
green "✅ Done. Next briefing fires at 8:00 Sydney time (Mon–Fri)."
bold "═══════════════════════════════════════════════"
echo ""
echo "  Customize:    nano $ENV_FILE"
echo "  Change time:  crontab -e"
echo "  Logs:         ~/.claude/logs/morning-briefing-YYYYMMDD.log"
echo "  Uninstall:    see $KIT_DIR/README.md"
echo ""
